#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch=$(git branch | grep '*' | sed 's/* //')

if [[ "$branch" = "main" || "$branch" = "develop" ]]; then
  echo "You can't commit directly to 'main' or 'develop' branch. Please create your own branch and use PR"
  exit 1
fi


npm run lintstaged
# npx stylelint 'src/**/*.css'
